In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/online-retail/Online_Retail.csv

In [3]:
df=pd.read_csv("/kaggle/input/online-retail/Online_Retail.csv",encoding='ISO-8859-1')

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [6]:
df.drop(['InvoiceNo',	'StockCode',	'Description'],axis=1)

        Quantity    InvoiceDate  UnitPrice  CustomerID         Country
0              6   12/1/10 8:26       2.55     17850.0  United Kingdom
1              6   12/1/10 8:26       3.39     17850.0  United Kingdom
2              8   12/1/10 8:26       2.75     17850.0  United Kingdom
3              6   12/1/10 8:26       3.39     17850.0  United Kingdom
4              6   12/1/10 8:26       3.39     17850.0  United Kingdom
...          ...            ...        ...         ...             ...
541904        12  12/9/11 12:50       0.85     12680.0          France
541905         6  12/9/11 12:50       2.10     12680.0          France
541906         4  12/9/11 12:50       4.15     12680.0          France
541907         4  12/9/11 12:50       4.15     12680.0          France
541908         3  12/9/11 12:50       4.95     12680.0          France

[541909 rows x 5 columns]

In [7]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [8]:
numeric_col=df.select_dtypes(include=['number'])

In [9]:
numeric_col

        Quantity  UnitPrice  CustomerID
0              6       2.55     17850.0
1              6       3.39     17850.0
2              8       2.75     17850.0
3              6       3.39     17850.0
4              6       3.39     17850.0
...          ...        ...         ...
541904        12       0.85     12680.0
541905         6       2.10     12680.0
541906         4       4.15     12680.0
541907         4       4.15     12680.0
541908         3       4.95     12680.0

[541909 rows x 3 columns]

In [10]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df['Description']=df['Description'].fillna(0)

In [42]:
df['CustomerID']=df['CustomerID'].fillna(0)

In [43]:
df.isnull().sum()

InvoiceNo                          0
StockCode                          0
Description                     1454
Quantity                           0
UnitPrice                          0
CustomerID                         0
Country_Austria                    0
Country_Bahrain                    0
Country_Belgium                    0
Country_Brazil                     0
Country_Canada                     0
Country_Channel Islands            0
Country_Cyprus                     0
Country_Czech Republic             0
Country_Denmark                    0
Country_EIRE                       0
Country_European Community         0
Country_Finland                    0
Country_France                     0
Country_Germany                    0
Country_Greece                     0
Country_Hong Kong                  0
Country_Iceland                    0
Country_Israel                     0
Country_Italy                      0
Country_Japan                      0
Country_Lebanon                    0
Country_Lithuania                  0
Country_Malta                      0
Country_Netherlands                0
Country_Norway                     0
Country_Poland                     0
Country_Portugal                   0
Country_RSA                        0
Country_Saudi Arabia               0
Country_Singapore                  0
Country_Spain                      0
Country_Sweden                     0
Country_Switzerland                0
Country_USA                        0
Country_United Arab Emirates       0
Country_United Kingdom             0
Country_Unspecified                0
Year                               0
Month                              0
Day                                0
Hour                               0
dtype: int64

In [11]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler=StandardScaler()

In [15]:
scaler.fit_transform(numeric_col)

array([[-0.01628867, -0.02130135,  1.49528019],
       [-0.01628867, -0.01262006,  1.49528019],
       [-0.00711777, -0.01923438,  1.49528019],
       ...,
       [-0.02545958, -0.00476555, -1.52176314],
       [-0.02545958, -0.00476555, -1.52176314],
       [-0.03004503,  0.00350235, -1.52176314]])

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [16]:

df = pd.get_dummies(df, columns=['Country'], drop_first=True)

In [32]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day
df['Hour'] = df['InvoiceDate'].dt.hour

df = df.drop('InvoiceDate', axis=1)

/tmp/ipykernel_126/145525266.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [33]:
x=df.drop(['Quantity',	'InvoiceNo'	,'StockCode',	'Description'],axis=1)
y=df['Quantity']

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [45]:
x_train.isna().sum()

UnitPrice                            0
CustomerID                      101250
Country_Austria                      0
Country_Bahrain                      0
Country_Belgium                      0
Country_Brazil                       0
Country_Canada                       0
Country_Channel Islands              0
Country_Cyprus                       0
Country_Czech Republic               0
Country_Denmark                      0
Country_EIRE                         0
Country_European Community           0
Country_Finland                      0
Country_France                       0
Country_Germany                      0
Country_Greece                       0
Country_Hong Kong                    0
Country_Iceland                      0
Country_Israel                       0
Country_Italy                        0
Country_Japan                        0
Country_Lebanon                      0
Country_Lithuania                    0
Country_Malta                        0
Country_Netherlands                  0
Country_Norway                       0
Country_Poland                       0
Country_Portugal                     0
Country_RSA                          0
Country_Saudi Arabia                 0
Country_Singapore                    0
Country_Spain                        0
Country_Sweden                       0
Country_Switzerland                  0
Country_USA                          0
Country_United Arab Emirates         0
Country_United Kingdom               0
Country_Unspecified                  0
Year                                 0
Month                                0
Day                                  0
Hour                                 0
dtype: int64

In [49]:
x_train.isna().sum()

UnitPrice                            0
CustomerID                      101250
Country_Austria                      0
Country_Bahrain                      0
Country_Belgium                      0
Country_Brazil                       0
Country_Canada                       0
Country_Channel Islands              0
Country_Cyprus                       0
Country_Czech Republic               0
Country_Denmark                      0
Country_EIRE                         0
Country_European Community           0
Country_Finland                      0
Country_France                       0
Country_Germany                      0
Country_Greece                       0
Country_Hong Kong                    0
Country_Iceland                      0
Country_Israel                       0
Country_Italy                        0
Country_Japan                        0
Country_Lebanon                      0
Country_Lithuania                    0
Country_Malta                        0
Country_Netherlands                  0
Country_Norway                       0
Country_Poland                       0
Country_Portugal                     0
Country_RSA                          0
Country_Saudi Arabia                 0
Country_Singapore                    0
Country_Spain                        0
Country_Sweden                       0
Country_Switzerland                  0
Country_USA                          0
Country_United Arab Emirates         0
Country_United Kingdom               0
Country_Unspecified                  0
Year                                 0
Month                                0
Day                                  0
Hour                                 0
dtype: int64

In [58]:
x_train['CustomerID']=x_train['CustomerID'].fillna(0)
x_test['CustomerID']=x_test['CustomerID'].fillna(0)

In [73]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor

In [74]:
models = {
    "Linear Regression": LinearRegression(),
    
    "Decision Tree": DecisionTreeRegressor(max_depth=5),
    "Random Forest": RandomForestRegressor(n_estimators=100),
    "XGB": XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)
    
}

In [75]:
for model_name in models.keys():
    models[model_name].fit(x_train,y_train)
    print(model_name)
    print(models[model_name].score(x_test,y_test))

Linear Regression
0.001400016086182121
Decision Tree
0.003269327386672294
Random Forest
-1.6701222018864588
XGB
-0.495364785194397

In [77]:

df_sub= pd.DataFrame()
df_sub['CustomerID']=df['CustomerID']
df_sub['Quantity']= models[model_name].predict(x)
df_sub.to_csv("sub.csv",index=False)